from flask import Flask, render_template, request, redirect, url_for, abort
import joblib
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import random

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/predict', methods= ['GET', 'POST'])
def predict():
    if request.method == 'POST':
        genre = int(request.form['genre'])
        duration = int(request.form['duration'])
        rating = int(request.form['rating'])

        if genre == 0:
            genre_Action = 1,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 1:
            genre_Action = 0,
            genre_Adventure = 1,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0

        elif genre == 2:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 1,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0

        elif genre == 3:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 1,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 4:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 1,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 5:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 1,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 6:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 1,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 7:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 1,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 8:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 1,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 9:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 1,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 10:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 1,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 11:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 1,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 12:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 1,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 13:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 1,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 14:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 1,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 15:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 1,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 16:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 1,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 17:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 1,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 18:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 1,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 19:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 1,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 20:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 1,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 21:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 1,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 22:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 1,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 23:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 1,
            genre_War = 0,
            genre_Western = 0
        
        elif genre == 24:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 1,
            genre_Western = 0
        
        elif genre == 25:
            genre_Action = 0,
            genre_Adventure = 0,
            genre_Animation = 0,
            genre_Biblical = 0,
            genre_Biography = 0,
            genre_Comedy = 0,
            genre_Crime = 0,
            genre_Documentary = 0,
            genre_Drama = 0,
            genre_Experimental = 0,
            genre_Fantasy = 0,
            genre_Gangster = 0,
            genre_Grotesque = 0,
            genre_History = 0,
            genre_Horror = 0,
            genre_Melodrama = 0,
            genre_Musical = 0,
            genre_Mythology = 0,
            genre_Noir = 0,
            genre_Romantic = 0,
            genre_Superhero = 0,
            genre_Sport = 0,
            genre_Spy = 0,
            genre_Thriller = 0,
            genre_War = 0,
            genre_Western = 1
    
    x_pred = [
        genre_Thriller[0],
        genre_Drama[0],
        genre_Horror[0],
        genre_Comedy[0],
        genre_Adventure[0],
        genre_Action[0],
        genre_Grotesque[0],
        genre_Fantasy[0],
        genre_War[0],
        genre_Musical[0],
        genre_Crime[0],
        genre_Spy[0],
        genre_Noir[0],
        genre_Biography[0],
        genre_Animation[0],
        genre_Western,
        genre_Documentary[0],
        genre_Romantic[0],
        genre_Superhero[0],
        genre_Melodrama[0],
        genre_Gangster[0],
        genre_Mythology[0],
        genre_Biblical[0],
        genre_History[0],
        genre_Experimental[0],
        genre_Sport[0],
        duration,
        rating
    ]
    
    print(x_pred)
    y_pred = modelDT.predict([x_pred])[0]
    index_input = dfFilm[dfFilm['film_title'] == y_pred].index.values[0]

    from sklearn.feature_extraction.text import CountVectorizer
    model = CountVectorizer(
        tokenizer= lambda x : x.split(' '),
        analyzer= 'word'
    )

    matrix = model.fit_transform(dfFilm['genre'])
    # feature = model.get_feature_names()

    from sklearn.metrics.pairwise import cosine_similarity
    score = cosine_similarity(matrix)

    all_films = list(enumerate(score[index_input]))

    rec_films = sorted(
        all_films,
        key= lambda i : i[1],
        reverse= True
    )

    similar_films = []
    for i in rec_films:
        if i[1] > 0.5:
            similar_films.append(i)

    random_rec = random.choices(similar_films, k= 3)
    
    list_film = []
    for i in random_rec:
        title = dfFilm.iloc[i[0]]['film_title'] 
        list_film.append(title)
        print(dfFilm.iloc[i[0]]['film_title'])
    
    return render_template('film.html', list_film = list_film)



if __name__ == '__main__':
    dfFilm = pd.read_csv('dfFilm.csv')
    modelDT = joblib.load('model')
    app.run(debug = True)